version: "3.2"
services:
  wms-service:
    # 容器名称
    container_name: wms-service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - EUREKA_URL=http://eureka:8761
      - DB_URL=jdbc:mysql://db:3306/wms-db?useUnicode=true&characterEncoding=utf-8&useSSL=false
      - DB_USER=root
      - DB_PASSWORD=12345678
      - LOGSTASH_URL=logstash:4560
    ports:
      - "8762:8762"
    depends_on:
      - eureka
      - logstash
      - db
    # 健康检查，启动后，当这个命令执行没问题，才会任何这个服务启动成功
    healthcheck:
      # 命令
      test: ["CMD", "curl", "-f", "http://localhost:8762/info"]
      # 间隔时间，安装应用的预计启动时间来设置。
      interval: 1m
      timeout: 10s
      # 重试次数
      retries: 5
  eureka:
    # 镜像地址
    image: eureka-server:1.0.0
    # 容器名称
    container_name: eureka-server
    ports:
      - "8761:8761"

  elasticsearch:
    platform: linux/x86_64
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTICSEARCH_NETWORK_HOST=0.0.0.0
  kibana:
    platform: linux/x86_64
    image: kibana:7.16.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  logstash:
    platform: linux/x86_64
    image: logstash:7.16.2
    container_name: logstash
    ports:
      - "4560:4560"
    command: logstash -e 'input { tcp { host => "0.0.0.0" port => "4560" mode => "server" codec => json_lines } } output { stdout{ codec => rubydebug } elasticsearch{ hosts => ["elasticsearch:9200"] index => "log4j-%{+YYYY.MM.dd}" document_type => "log4j_type" } }'
    depends_on:
      - elasticsearch
  jaeger:
    image: jaegertracing/all-in-one:1.40
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=wms-db
    ports:
      - "3306:3306"
  postman:
    image: postman/newman
    volumes:
      - "./src/test/postman:/etc/newman"
    command: ["run", "wms.postman_collection.json", "-g", "WMS-SERVICE-LOCAL.postman_environment.json"]

volumes:
  db-data: