info:
  name: wms-service
  contact: jinku

server:
  port: 8762

spring:
  application:
    name: wms-service

  datasource:
    url: jdbc:mysql://localhost:3306/wms-db
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: ${DB_URL}
  #    username: ${DB_USER}
  #    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      # 自动创建表
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    # 服务列表缓存更新时间
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
  #      defaultZone: ${EUREKA_URL}/eureka/

  instance:
    # 心跳间隔
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
